
-------LEAD & LAG
SELECT * FROM employees


SELECT EMP_NAME, GENDER, SALARY,
LEAD (SALARY) OVER (ORDER BY SALARY) AS LEAD
FROM employees

SELECT EMP_NAME, GENDER, SALARY,
LAG (SALARY) OVER (ORDER BY SALARY) AS LAG
FROM employees

SELECT EMP_NAME, GENDER, SALARY,
LEAD (SALARY, 1, 2) OVER (ORDER BY SALARY) AS LEAD
FROM employees

SELECT EMP_NAME, GENDER, SALARY,
LAG (SALARY, 1, 18) OVER (ORDER BY SALARY) AS LAG
FROM employees

SELECT EMP_NAME, GENDER, SALARY,
LEAD (SALARY, 1, 2) OVER (PARTITION BY GENDER ORDER BY SALARY) AS LEAD,
LAG (SALARY, 1, 2) OVER (PARTITION BY GENDER ORDER BY SALARY) AS LAG
FROM employees

----------------TRIGGERS---------------------------

CREATE TABLE MAIN
(
ID INT,
SALARY MONEY
)

CREATE TABLE BACKUP_MAIN 
(
ID INT,
SALARY MONEY
)

INSERT INTO MAIN VALUES (12, 35000), (13, 45000), (14, 55000)

SELECT * FROM MAIN

CREATE TRIGGER TRIGGER_OF_DELETE
ON MAIN
FOR DELETE
AS
BEGIN
DECLARE @IDTT INT
DECLARE @SALARYTT MONEY
SELECT @IDTT = ID, @SALARYTT = SALARY FROM DELETED
INSERT INTO BACKUP_MAIN VALUES (@IDTT, @SALARYTT)
END

DELETE FROM MAIN
WHERE ID = 13

SELECT  * FROM MAIN
SELECT * FROM BACKUP_MAIN





