CREATE TABLE BRANCH
(
B_CODE INT,
B_NAME VARCHAR (100),
B_ADDRESS CHAR (100)
)

SELECT * FROM BRANCH

BEGIN TRANSACTION
INSERT INTO BRANCH VALUES (101, 'PNB BANK', 'PUNE')

----TESTING------

BEGIN TRANSACTION
ROLLBACK

-------------
BEGIN TRANSACTION
INSERT INTO BRANCH VALUES (102, 'AXIS', 'MUMBAI'), (103, 'SBI', 'CHENNAI')

BEGIN TRANSACTION
INSERT INTO BRANCH VALUES (104, 'KMB', 'DELHI')

ROLLBACK

BEGIN TRANSACTION
INSERT INTO BRANCH VALUES (105, 'KGB', 'DELHI')
COMMIT /*SAVE*/

SELECT * FROM BRANCH

------DELETE(ROLLBACK)--DML & DROP, TRUNCATE ARE DDL
BEGIN TRANSACTION
DELETE FROM BRANCH WHERE B_CODE = 105

----------------------DCL-------------------

---GRANT SELECT, INSERT, UPDATE ON TABLE EMPLOYEES TO PURSHIPRABHAS@COACHX

----GRANT BASED ON ROLES

----CREATE ROLE ----
-----DROP ROLE------

--------------------------------------------------------------
----WRITE A QUERY TO DISPLAY MAX SALARY FROM EMPLOYEES 
SELECT * FROM employees

SELECT MAX (SALARY) FROM employees

----WRITE A QUERY TO DISPLAY MAX SALARY WITH DEPT NAME FROM EMPLOYEES 


SELECT EMP_NAME,   MAX (salary) FROM employees
GROUP BY emp_name
ORDER BY MAX_OF_SALARY DESC













