select * from STUDENTS

select * from COURSE

SELECT * FROM STUDENTS--------LEFT TABLE
FULL OUTER JOIN
COURSE ------RIGHT TABLE
ON
STUDENTS.COURSE_ID=COURSE.COURSE_ID

SELECT * FROM STUDENTS
CROSS JOIN
COURSE

-----------ALIAS 

SELECT * FROM STUDENTS AS S --------LEFT TABLE
FULL OUTER JOIN
COURSE AS C ------RIGHT TABLE
ON
S.COURSE_ID=C.COURSE_ID

-------UPDATE
UPDATE STUDENTS
SET STD_NAME = 'PRABHA'
WHERE STD_ID = 3

UPDATE STUDENTS
SET STD_CITY = 'MUMBAI', COURSE_ID = 105
WHERE STD_ID = 3

SELECT * FROM STUDENTS

--------DELETE TRUNCATE DROP--

DELETE FROM STUDENTS

WHERE STD_NAME = 'JAM'

SELECT * FROM STUDENTS

--------
TRUNCATE TABLE STUDENTS

SELECT * FROM STUDENTS
--------------------
UPDATE STUDENTS
SET STD_CITY = 'KOLKATA'
WHERE STD_ID = 2

UPDATE STUDENTS
SET STD_NAME = 'PAPI'
WHERE STD_ID = 3

SELECT * FROM STUDENTS

----------------
DROP TABLE STUDENTS
-------------------
---------ALTER---
ALTER TABLE DEPARTMENT
ADD EMP_NAME VARCHAR (100)

ALTER TABLE DEPARTMENT
DROP COLUMN EMP_NAME

SELECT * FROM DEPARTMENT



